name: Update Recent Activity
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --global user.name "Prashant Kumar"
          git config --global user.email "prashantkumar18.pk@gmail.com"
          git add README.md
          git commit -m "Update recent activity"
          git push
